from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from .. import schemas, models
from ..database import get_db
from services.rag_pipeline import generate_questions
from services.ml_engine import analyze_assignment_pedagogy
import uuid

router = APIRouter()

@router.post("/generate")
async def generate_assignment_content(request: schemas.GenerateRequest):
    """
    Called by AssignmentCreator.tsx
    Receives: { topic, type, difficulty }
    Returns: list of questions generated by RAG
    """
    questions = await generate_questions(request.topic, request.difficulty, request.type)
    return questions

@router.post("/create")
def create_assignment(assignment: schemas.AssignmentCreate, db: Session = Depends(get_db)):
    """
    Saves the final approved assignment to Postgres
    """
    db_assignment = models.Assignment(
        id=assignment.id,
        title=assignment.title,
        subject=assignment.subject,
        topic=assignment.topic,
        type=assignment.type,
        difficulty=assignment.difficulty,
        questions=assignment.questions, # JSON
        status="Draft"
    )
    db.add(db_assignment)
    db.commit()
    return {"status": "success", "id": assignment.id}

@router.post("/{id}/analyze")
async def analyze_assignment(id: str, db: Session = Depends(get_db)):
    """
    Called by AssignmentsList.tsx for 'AI Audit'
    """
    assignment = db.query(models.Assignment).filter(models.Assignment.id == id).first()
    if not assignment:
        # Fallback for mock data IDs if not in DB
        return {"id": id, "text": "Mock analysis: Excellent coverage of topic."}
    
    result = await analyze_assignment_pedagogy(assignment.__dict__)
    return {"id": id, "text": result}